export const INITIAL_STATE = 'INITIAL_STATE';

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';

export const MARK_UNSAFE_PAYMENT_SUCCESS = 'MARK_UNSAFE_PAYMENT_SUCCESS';