// <auto-generated />
using System;
using DBRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DBRepository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190108100522_Migration0")]
    partial class Migration0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Models.CardPayment", b =>
                {
                    b.Property<Guid>("CardPaymentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardNumber");

                    b.Property<string>("Comment");

                    b.Property<string>("Cvc");

                    b.Property<string>("Email");

                    b.Property<string>("Expiration");

                    b.Property<bool>("IsSafe");

                    b.Property<decimal>("Sum");

                    b.HasKey("CardPaymentId");

                    b.ToTable("CardPayments");
                });

            modelBuilder.Entity("Models.PaymentRequest", b =>
                {
                    b.Property<Guid>("PaymentRequestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNumber");

                    b.Property<string>("Bic");

                    b.Property<string>("Email");

                    b.Property<string>("Inn");

                    b.Property<string>("Phone");

                    b.Property<decimal>("Sum");

                    b.Property<int>("Vat");

                    b.HasKey("PaymentRequestId");

                    b.ToTable("PaymentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
